# Site settings
title: "Carlo Leonardi"
email: "c.leonardi95@protonmail.com"
description: "Computational Immunology, AI, Computational Biology"
twitter_username: "CarloLeonardi7"
github_username: "carloelle"
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown

# Use Minimal Mistakes as a remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages

# Plugins (GitHub Pages–friendly)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Carlo Leonardi"
  avatar : "/img/header.jpg"   # or wherever your image really lives
  bio    : "Bioinformatics, Data Science, AI"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url:  "mailto:c.leonardi95@protonmail.com"
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/CarloLeonardi7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/carloelle"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=K723OxUAAAAJ&hl=en"

footer:
  links:
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/CarloLeonardi7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url:  "https://github.com/carloelle"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=K723OxUAAAAJ&hl=en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
