title: "Carlo Leonardi"
description: "Computational Immunology, AI, Computational Biology"
email: "c.leonardi95@protonmail.com"
lang: en-GB

remote_theme: benbalter/retlab

permalink: pretty
timezone: Europe/London

include:
  - _pages

nav_pages:
  - index.html
  - about.md


contact_links:
  - name: Email
    url: "mailto:c.leonardi95@protonmail.com"
    icon: envelope
  - name: GitHub
    url: "https://github.com/carloelle"
    icon: github
  - name: X
    url: "https://x.com/CarloLeonardi7"
    icon: twitter
  - name: Google Scholar
    url: "https://scholar.google.com/citations?user=K723OxUAAAAJ&hl=en"
    icon: graduation-cap


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false


plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate


exclude:
  - vendor/bundle/
  - node_modules/
  - js/
  - sass/
  - script/
  - prettier.config.js
  - "*.gem"
  - "*.gemspec"
  - "*.json"
  - "*.ts"
